# Generated by Django 6.0.3 on 2026-03-19 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_transaction_due_date_alertnotification"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="alertnotification",
            new_name="core_alertn_is_acti_5bf0c1_idx",
            old_name="core_alertno_is_acti_e80787_idx",
        ),
        migrations.RenameIndex(
            model_name="alertnotification",
            new_name="core_alertn_source__b97bb8_idx",
            old_name="core_alertno_source__de4e60_idx",
        ),
        migrations.RenameIndex(
            model_name="alertnotification",
            new_name="core_alertn_due_dat_92bd51_idx",
            old_name="core_alertno_due_dat_a0242f_idx",
        ),
    ]
