# Generated by Django 6.0.3 on 2026-03-21 02:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_customer_credit_balance_customerpayment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JCBRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("start_time", models.DecimalField(decimal_places=1, max_digits=4)),
                ("end_time", models.DecimalField(decimal_places=1, max_digits=4)),
                (
                    "total_work_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("paid", "Paid")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=2000, max_digits=12),
                ),
                ("expense_item", models.CharField(blank=True, max_length=120)),
                (
                    "expense_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(fields=["date"], name="core_jcbrec_date_f0c15d_idx"),
                    models.Index(
                        fields=["status"], name="core_jcbrec_status_a6fd06_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="jcb_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="core.jcbrecord",
            ),
        ),
    ]
