# Generated by Django 6.0.3 on 2026-03-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_jcbrecord_transaction_jcb_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="jcbrecord",
            name="site_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="jcbrecord",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
        migrations.AlterField(
            model_name="jcbrecord",
            name="end_time",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name="jcbrecord",
            name="start_time",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name="jcbrecord",
            name="total_work_hours",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
