# Generated by Django 6.0.3 on 2026-03-21 11:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_jcbrecord_site_name_jcbrecord_total_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jcbrecord",
            name="end_time",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=7
            ),
        ),
        migrations.AlterField(
            model_name="jcbrecord",
            name="start_time",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=7
            ),
        ),
    ]
