# Generated by Django 6.0.3 on 2026-03-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_jcbrecord_end_time_alter_jcbrecord_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="manual_due_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Manually added due amount for legacy/existing dues",
                max_digits=14,
            ),
        ),
    ]
