# Generated by Django 5.2.4 on 2026-03-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_tipperitem_tipperrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertnotification",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("overdue", "Overdue"),
                    ("upcoming", "Upcoming"),
                    ("manual", "Manual"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="alertnotification",
            name="source_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="alertnotification",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("sale", "Sale"),
                    ("transaction", "Transaction"),
                    ("manual", "Manual"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="alertnotification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_type", "manual")),
                fields=("customer", "due_date", "title", "source_type"),
                name="core_alertn_manual_customer_due_title_uniq",
            ),
        ),
    ]
