# Generated by Django 5.2.4 on 2026-03-25 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_alertnotification_alert_type_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="alertnotification",
            name="core_alertn_manual_customer_due_title_uniq",
        ),
        migrations.AlterField(
            model_name="alertnotification",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alert_notifications",
                to="core.customer",
            ),
        ),
        migrations.AddConstraint(
            model_name="alertnotification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_type", "manual")),
                fields=("due_date", "title", "source_type"),
                name="core_alertn_manual_due_title_uniq",
            ),
        ),
    ]
