# Generated by Django 6.0.3 on 2026-04-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0017_remove_alertnotification_core_alertn_manual_customer_due_title_uniq_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tipperrecord",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
