# Generated by Django 6.0.3 on 2026-04-15 08:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_cementrecord_transaction_cement_record"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cementrecord",
            new_name="core_cement_date_23759c_idx",
            old_name="core_cement_date_4c3f77_idx",
        ),
        migrations.RenameIndex(
            model_name="cementrecord",
            new_name="core_cement_record__245956_idx",
            old_name="core_cement_record_3de1e0_idx",
        ),
        migrations.RenameIndex(
            model_name="cementrecord",
            new_name="core_cement_unit_ty_228ebf_idx",
            old_name="core_cement_unit_t_8c7fb6_idx",
        ),
    ]
