# Generated by Django 6.0.3 on 2026-04-15 09:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "core",
            "0023_rename_core_cement_date_4c3f77_idx_core_cement_date_23759c_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BambooRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("investment", "Investment"),
                            ("stock", "Stock (Addition)"),
                            ("sale", "Sale"),
                        ],
                        help_text="Type of record: investment, stock inventory update, or sale",
                        max_length=20,
                    ),
                ),
                (
                    "investment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Amount spent on bamboo procurement or processing",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "sale_income",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Auto-calculated: quantity × price (for sale records)",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of units (for stock addition or sale)",
                        null=True,
                    ),
                ),
                (
                    "price_per_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price per unit (for sale records)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional details or remarks"
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(fields=["date"], name="core_bamboo_date_e25eb2_idx"),
                    models.Index(
                        fields=["record_type"], name="core_bamboo_record__b2fcb6_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="transaction",
            name="bamboo_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="core.bamboorecord",
            ),
        ),
    ]
