# Generated by Django 6.0.3 on 2026-04-22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_add_payment_status_to_material_records"),
    ]

    operations = [
        migrations.AddField(
            model_name="bamboorecord",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned customer for sale records",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bamboo_records",
                to="core.customer",
            ),
        ),
        migrations.AddField(
            model_name="blocksrecord",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned customer for sale records",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="blocks_records",
                to="core.customer",
            ),
        ),
        migrations.AddField(
            model_name="cementrecord",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned customer for sale records",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cement_records",
                to="core.customer",
            ),
        ),
    ]
