# Generated by Django 5.2.4 on 2026-05-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_jcbrecord_paid_amount_jcbrecord_pending_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="expense_credit_applied",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="transaction",
            name="expense_due_remainder",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
