from django.urls import path

from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("cash-entries/", views.cash_entries, name="cash_entries"),
    path("cash-entries/new/", views.transaction_create, name="transaction_create"),
    path("cash-entries/<int:pk>/", views.transaction_detail, name="transaction_detail"),
    path("cash-entries/<int:pk>/edit/", views.transaction_edit, name="transaction_edit"),
    path("cash-entries/<int:pk>/delete/", views.transaction_delete, name="transaction_delete"),
    path("sales/", views.sales, name="sales"),
    path("sales/new/", views.sale_create, name="sale_create"),
    path("sales/<int:pk>/", views.sale_detail, name="sale_detail"),
    path("sales/<int:pk>/edit/", views.sale_edit, name="sale_edit"),
    path("sales/<int:pk>/toggle-alert/", views.sale_toggle_alert, name="sale_toggle_alert"),
    path("sales/<int:pk>/mark-paid/", views.sale_mark_paid, name="sale_mark_paid"),
    path("sales/<int:pk>/delete/", views.sale_delete, name="sale_delete"),
    path("sales/<int:pk>/receipts/add/", views.sale_receipt_create, name="sale_receipt_create"),
    path("jcb-records/", views.jcb_records, name="jcb_records"),
    path("jcb-records/new/", views.jcb_record_create, name="jcb_record_create"),
    path("jcb-records/<int:pk>/edit/", views.jcb_record_edit, name="jcb_record_edit"),
    path("jcb-records/<int:pk>/mark-paid/", views.jcb_record_mark_paid, name="jcb_record_mark_paid"),
    path("jcb-records/<int:pk>/delete/", views.jcb_record_delete, name="jcb_record_delete"),
    path("tipper-records/", views.tipper_records, name="tipper_records"),
    path("tipper-records/new/", views.tipper_record_create, name="tipper_record_create"),
    path("tipper-records/<int:pk>/", views.tipper_record_detail, name="tipper_record_detail"),
    path("tipper-records/<int:pk>/edit/", views.tipper_record_edit, name="tipper_record_edit"),
    path("tipper-records/<int:pk>/delete/", views.tipper_record_delete, name="tipper_record_delete"),
    path("customers/", views.customers, name="customers"),
    path("customers/new/", views.customer_create, name="customer_create"),
    path("customers/<int:pk>/", views.customer_detail, name="customer_detail"),
    path(
        "customers/<int:pk>/allocate-payment/",
        views.customer_allocate_payment,
        name="customer_allocate_payment",
    ),
    path("customers/<int:pk>/edit/", views.customer_edit, name="customer_edit"),
    path("customers/<int:pk>/delete/", views.customer_delete, name="customer_delete"),
    path("alerts/", views.alerts, name="alerts"),
    path("alerts/manual/new/", views.manual_alert_create, name="manual_alert_create"),
    path("alerts/manual/<int:pk>/edit/", views.manual_alert_edit, name="manual_alert_edit"),
    path("alerts/manual/<int:pk>/delete/", views.manual_alert_delete, name="manual_alert_delete"),
    path("alerts/badge/", views.alerts_badge, name="alerts_badge"),
    path(
        "alerts/notifications/<int:pk>/resolve/",
        views.alert_notification_resolve,
        name="alert_notification_resolve",
    ),
    path("cement-records/", views.cement_records, name="cement_records"),
    path("cement-records/new/", views.cement_record_create, name="cement_record_create"),
    path("cement-records/<int:pk>/edit/", views.cement_record_edit, name="cement_record_edit"),
    path("cement-records/<int:pk>/delete/", views.cement_record_delete, name="cement_record_delete"),
    path("bamboo-records/", views.bamboo_records, name="bamboo_records"),
    path("bamboo-records/new/", views.bamboo_record_create, name="bamboo_record_create"),
    path("bamboo-records/<int:pk>/edit/", views.bamboo_record_edit, name="bamboo_record_edit"),
    path("bamboo-records/<int:pk>/delete/", views.bamboo_record_delete, name="bamboo_record_delete"),
    path("blocks-records/", views.blocks_records, name="blocks_records"),
    path("blocks-records/new/", views.blocks_record_create, name="blocks_record_create"),
    path("blocks-records/<int:pk>/edit/", views.blocks_record_edit, name="blocks_record_edit"),
    path("blocks-records/<int:pk>/delete/", views.blocks_record_delete, name="blocks_record_delete"),
]
